config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :show]
  resources :chats, only: [:index, :show]
  resources :messages, only: [:index, :show]

  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
    @chats = Chat.all
  end
  def show
    @chat = Chat.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end

  def show
    @message = Message.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/index.html.erb
<h1>Chats</h1>

<table>
  <thead>
    <tr>
      <th>Sender</th>
      <th>Receiver</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @chats.each do |chat| %>
      <tr>
        <td><%= chat.sender_id %></td>
        <td><%= chat.receiver_id %></td>
        <td><%= link_to "Show", chat_path(chat) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/chats/show.html.erb
<h1>Chat Details</h1>

<p>Sender: <%= @chat.sender_id %></p>
<p>Receiver: <%= @chat.receiver_id %></p>

<%= link_to 'Back to Chats', chats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Your App</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Lab 6</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Users", users_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Chats", chats_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", messages_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <%= yield %>
</body>
</html>

app/views/messages/index.html.erb
<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.body %></td>
        <td><%= link_to "Show", message_path(message) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/messages/show.html.erb
<h1>Message Details</h1>

<p>Body: <%= @message.body %></p>

<%= link_to 'Back to Messages', messages_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to "Show", user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<h1>User Details</h1>

<p>Email: <%= @user.email %></p>
<p>First Name: <%= @user.first_name %></p>
<p>Last Name: <%= @user.last_name %></p>

<%= link_to 'Back to Users', users_path %>